"""Añade modelo Rol y relación con Miembro

Revision ID: 7d37a31fbb10
Revises: a70ad8c56024
Create Date: 2025-09-17 13:37:05.258494

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7d37a31fbb10'
down_revision = 'a70ad8c56024'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre_completo', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('rol_id', sa.Integer(), nullable=True))
        batch_op.alter_column('fecha_ingreso',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.drop_index(batch_op.f('fullname'))
        batch_op.drop_index(batch_op.f('rol'))
        batch_op.create_foreign_key(None, 'roles', ['rol_id'], ['id'])
        batch_op.drop_column('fullname')
        batch_op.drop_column('rol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rol', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=False))
        batch_op.add_column(sa.Column('fullname', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('rol'), ['rol'], unique=True)
        batch_op.create_index(batch_op.f('fullname'), ['fullname'], unique=True)
        batch_op.alter_column('fecha_ingreso',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('rol_id')
        batch_op.drop_column('nombre_completo')

    op.drop_table('roles')
    # ### end Alembic commands ###
