"""Agrego columnas email y descripcion en modelo Miembro

Revision ID: 8be341f6ef2c
Revises: 7d37a31fbb10
Create Date: 2025-09-18 10:55:37.371446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be341f6ef2c'
down_revision = '7d37a31fbb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('descripcion', sa.String(length=200), nullable=True))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('descripcion')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
