"""Añade campo foto_perfil a Miembro

Revision ID: 92fc6f8a9c97
Revises: 8be341f6ef2c
Create Date: 2025-09-18 14:27:58.027504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92fc6f8a9c97'
down_revision = '8be341f6ef2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')

    # ### end Alembic commands ###
