"""Añade relación jerárquica a Miembro

Revision ID: cb8c0d0bba19
Revises: 92fc6f8a9c97
Create Date: 2025-09-22 17:15:36.002173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb8c0d0bba19'
down_revision = '92fc6f8a9c97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'miembros', ['lider_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('miembros', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lider_id')

    # ### end Alembic commands ###
